### ISSUE TITLE
Login page title

### ISSUE THREAD

**Issue by Raffelke** [ZuydUniversity/B2C6_HERKANSING_FRONTEND#11]
Maak een titel voor het inlogscherm met een speciaal lettertype en mogelijkheden voor meerdere lettergroottes (hoofdtitel, middelgroot en normaal) voor zowel titels als tekstfonts in CSS en TSX. Voeg ook een aangepast effect toe aan de hoofdtitel van de app.

**Comment by TrueProvidence** [comment]
Can't review without a pull request
