### ISSUE TITLE
Maak PickaxeButton

### ISSUE THREAD

**Issue by Raffelke** [ZuydUniversity/B2C6_HERKANSING_FRONTEND#7]

**Comment by TrueProvidence** [comment]
Je bent vergeten je branch te koppelen. Dat doe je bij development hier rechts: 
![afbeelding](https://github.com/user-attachments/assets/eb4ef768-5406-4575-85ca-02857e5fa927)
daar kies je de repo en branch. Het handigste is om met de issue te beginnen en daaruit je branch te maken tho

**Comment by TrueProvidence** [comment]
Ik heb 'm voor nu alvast voor je gerkoppeld. Feel free to make a pull request so I can review it
